    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-express-app
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: my-express-app
      template:
      metadata:
          labels:
            app: my-express-app
        spec:
          containers:
          - name:  my-express-app
            image: docker.io/thiagohprado/my-express-app:latest # Imagem construída com o Dockerfile no teste 1
            ports:
            - containerPort: 3001
            volumeMounts:
              - name: volume-log
                mountPath: /app/logs # O caminho dentro do contêiner onde os logs serão salvos
          volumes:
          - name: volume-log
            persistentVolumeClaim:
              claimName: pvc-log

---
apiVersion: v1
kind: Service
metadata:
  name: my-express-app
spec:
  selector:
    app: my-express-app
  ports:
    - port: 3001


---
        apiVersion: v1
        kind: PersistentVolume
        metadata:
          name: volume-log
        spec:
          capacity:
            storage: 100m
          accessModes:
            - ReadWriteOnce # Permite leitura/gravação por um único nó
          # storageClassName: "" 
          hostPath: # Use apenas para desenvolvimento e teste
            path: "/mnt/data"


---
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: pvc-log
        spec:
          accessModes:
            - ReadWriteOnce
          #storageClassName: "provisionador-padrao" # Nome da StorageClass para provisionamento dinâmico
         #resources:
          #  requests:
            #  storage: 5Gi
          # hostPath: # Use apenas para desenvolvimento e teste
           # path: "/mnt/data"
