name: CI-CD

on:
  push:
    branches: ["main"]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with: 
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Build da imagem
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            thiagohprado/my-express-app:latest
            thiagohprado/my-express-app:${{github.run_number}}



  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}}

       - name: Deploy to Kubernetes cluster
         uses: Azure/k8s-deploy@v4.9
         with:
          images: thiagohprado/my-express-app:${{github.run_number}}
          manifests: |
            k8s/app.yaml
    
