name: Continuous Integration

on:
  push:
    branches: ["main"]
    
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with: 
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Build da imagem
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
            thiagohprado/my-express-app:${{github.run.number}}
